/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingDto } from "./trainingDto";

export interface GetListResponse {
  trainings: TrainingDto[];
  total: number;
}
