/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */

export interface GetListFilters {
  gymIds?: string[];
  groupIds?: string[];
  trainerIds?: string[];
  startDate?: string;
}
