/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */
import type { PageParameter } from "./pageParameter";
import type { LimitParameter } from "./limitParameter";
import type { SearchParameter } from "./searchParameter";
import type { SortOrderParameter } from "./sortOrderParameter";
import type { GetListFiltersParameter } from "./getListFiltersParameter";

export type GetListParams = {
  /**
   * Page number
   */
  page?: PageParameter;
  /**
   * Limit number of trainings per page
   */
  limit?: LimitParameter;
  /**
   * Search query
   */
  search?: SearchParameter;
  /**
   * Sort order
   */
  sortOrder?: SortOrderParameter;
  /**
   * Filters
   */
  filters?: GetListFiltersParameter;
};
