/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */
import type { GetListRequestSortBy } from "./getListRequestSortBy";
import type { GetListRequestSortOrder } from "./getListRequestSortOrder";
import type { GetListFilters } from "./getListFilters";

export interface GetListRequest {
  page?: number;
  limit?: number;
  search?: string;
  sortBy?: GetListRequestSortBy;
  sortOrder?: GetListRequestSortOrder;
  filters?: GetListFilters;
}
