/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */

export type GetListRequestSortOrder =
  (typeof GetListRequestSortOrder)[keyof typeof GetListRequestSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListRequestSortOrder = {
  asc: "asc",
  desc: "desc",
} as const;
