/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */

export type GetListRequestSortBy =
  (typeof GetListRequestSortBy)[keyof typeof GetListRequestSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListRequestSortBy = {
  id: "id",
  name: "name",
  startDate: "startDate",
} as const;
