/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */

export type SortOrderParameter =
  (typeof SortOrderParameter)[keyof typeof SortOrderParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOrderParameter = {
  asc: "asc",
  desc: "desc",
} as const;
