/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Training API
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingDtoTrainersItem } from "./trainingDtoTrainersItem";

export interface TrainingDto {
  id?: string;
  name?: string;
  startDate?: string;
  gymName?: string;
  groupName?: string;
  trainers?: TrainingDtoTrainersItem[];
}
