/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type AssignRoleRequestType =
  (typeof AssignRoleRequestType)[keyof typeof AssignRoleRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignRoleRequestType = {
  TRAINER: "TRAINER",
  TRAINEE: "TRAINEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
  SUPERADMIN: "SUPERADMIN",
} as const;
