/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */
import type { InitializeRoleRequestRole } from "./initializeRoleRequestRole";

export interface InitializeRoleRequest {
  role: InitializeRoleRequestRole;
}
