/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRoleType } from "./userRoleType";

export interface UserRole {
  type: UserRoleType;
}
