/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const registerUserBodyPasswordMin = 6;

export const registerUserBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(registerUserBodyPasswordMin),
  name: zod.string(),
  username: zod.string(),
});

export const confirmEmailBodyCodeMin = 6;

export const confirmEmailBodyCodeMax = 6;

export const confirmEmailBody = zod.object({
  email: zod.string().email(),
  code: zod.string().min(confirmEmailBodyCodeMin).max(confirmEmailBodyCodeMax),
});

export const confirmEmailResponse = zod.object({
  message: zod.string(),
});

export const loginUserBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const loginUserResponse = zod.object({
  accessToken: zod.string(),
  user: zod.object({
    id: zod.string(),
    email: zod.string(),
    name: zod.string(),
    activeRole: zod.enum([
      "TRAINER",
      "TRAINEE",
      "PARENT",
      "ADMIN",
      "SUPERADMIN",
    ]),
    isEmailConfirmed: zod.boolean(),
  }),
});

export const refreshTokenResponse = zod.object({
  accessToken: zod.string(),
  user: zod.object({
    id: zod.string(),
    email: zod.string(),
    name: zod.string(),
    activeRole: zod.enum([
      "TRAINER",
      "TRAINEE",
      "PARENT",
      "ADMIN",
      "SUPERADMIN",
    ]),
    isEmailConfirmed: zod.boolean(),
  }),
});

export const googleAuthBody = zod.object({
  token: zod.string().describe("Google ID token"),
});

export const googleAuthResponse = zod.object({
  accessToken: zod.string(),
  user: zod.object({
    id: zod.string(),
    email: zod.string(),
    name: zod.string(),
    activeRole: zod.enum([
      "TRAINER",
      "TRAINEE",
      "PARENT",
      "ADMIN",
      "SUPERADMIN",
    ]),
    isEmailConfirmed: zod.boolean(),
  }),
});

export const logoutUserResponse = zod.object({
  message: zod.string().optional(),
});

export const logoutAllDevicesResponse = zod.object({
  message: zod.string().optional(),
});
