/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getTrainerProfileResponse = zod.object({
  id: zod.string(),
  userId: zod.string(),
});

export const createTrainerProfileBody = zod.object({
  specialization: zod.string().optional(),
  experience: zod.number().optional(),
  description: zod.string().optional(),
  achievements: zod.array(zod.string()).optional(),
});

export const createTrainerProfileResponse = zod.object({
  id: zod.string(),
});
