/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachToTrainingResponseStatus } from "./attachToTrainingResponseStatus";

export interface AttachToTrainingResponse {
  status: AttachToTrainingResponseStatus;
}
