/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGymsRequestGymsItem } from "./createGymsRequestGymsItem";

export interface CreateGymsRequest {
  trainerId: string;
  gyms: CreateGymsRequestGymsItem[];
}
