/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSubscriptionsSubscriptionsItem } from "./createSubscriptionsSubscriptionsItem";

export interface CreateSubscriptions {
  trainerId: string;
  subscriptions: CreateSubscriptionsSubscriptionsItem[];
}
