/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type CreateGymsRequestGymsItem = {
  name: string;
  address: string;
  geoLat?: number;
  geoLng?: number;
  workHours?: string;
};
