/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContactInformationSocialsItem } from "./createContactInformationSocialsItem";

export interface CreateContactInformation {
  trainerId: string;
  emails?: string[];
  phoneNumbers?: string[];
  socials?: CreateContactInformationSocialsItem[];
}
