/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { PersistContactInformationSocialsItem } from "./persistContactInformationSocialsItem";

export interface PersistContactInformation {
  trainerId: string;
  emails?: string[];
  phoneNumbers?: string[];
  aboutMe?: string;
  socials?: PersistContactInformationSocialsItem[];
}
