/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type SortOrderParamParameter =
  (typeof SortOrderParamParameter)[keyof typeof SortOrderParamParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOrderParamParameter = {
  asc: "asc",
  desc: "desc",
} as const;
