/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingDtoType } from "./trainingDtoType";

export interface TrainingDto {
  /** Name of the training */
  name: string;
  /** Type of the training */
  type?: TrainingDtoType;
  /** Start date and time of the training */
  startDate?: string;
  /** Duration of the training in minutes */
  durationMin?: number;
  /** ID of the gym where training takes place */
  gymId?: string;
  /** ID of the group for group training */
  groupId?: string;
  /** ID of the training template */
  templateId?: string;
  /** Array of trainer IDs for the training */
  trainerIds?: string[];
}
